apiVersion: v1
kind: Service
metadata:
  name: pacman-actual
  labels:
    name: pacman
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: pacman
