apiVersion: v1
kind: Service
metadata:
  name: pacman
  labels:
    name: pacman
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4180
      protocol: TCP
  selector:
    k8s-app: oauth2-proxy
